import 'package:syntic_earth/views/widgets/chat_items.dart';

final List<ChatItem> chats = [
  ChatItem(
    name: 'Rexie',
    message: 'How are you?',
    time: '2:00 AM',
    unreadCount: 10,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.sent,
  ),
  ChatItem(
    name: 'Alex',
    message: '...Typing',
    time: '2:00 AM',
    unreadCount: 10,
    isTyping: true,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.sent,
  ),
  ChatItem(
    name: 'Tyler',
    message: 'How are you?',
    time: '7:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: true,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.delivered,
  ),
  ChatItem(
    name: 'Alan',
    message: 'How are you?',
    time: '7:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: true,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
  ChatItem(
    name: 'Mufasa',
    message: 'How are you?',
    time: '3:00 AM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.delivered,
  ),
  ChatItem(
    name: 'Alex',
    message: 'How are you?',
    time: '9:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
  ChatItem(
    name: 'Alex',
    message: 'How are you?',
    time: '9:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
  ChatItem(
    name: 'Alex',
    message: 'How are you?',
    time: '9:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
  ChatItem(
    name: 'Alex',
    message: 'How are you?',
    time: '9:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
  ChatItem(
    name: 'Alex',
    message: 'How are you?',
    time: '9:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
  ChatItem(
    name: 'Alex',
    message: 'How are you?',
    time: '9:00 PM',
    unreadCount: 0,
    isTyping: false,
    isSelected: false,
    avatar: 'assets/images/user.jpg',
    messageStatus: MessageStatus.seen,
  ),
];
